name-template: 'lagoon-images $NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: 'Package Updates'
    labels:
      - 'dependencies'

exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## New Images

  ## Changes in this release
  $CHANGES
